export default {
  "-- 1": {
    type: "separator",
    title: "Learn",
  },
  index: "Introduction",
  schema: "Schemas and Types",
  queries: "",
  mutations: "",
  subscriptions: "",
  validation: "",
  execution: "",
  response: "",
  introspection: "",
  "-- 2": {
    type: "separator",
    title: "Best Practices",
  },
  "best-practices": "",
  "thinking-in-graphs": "",
  "serving-over-http": "",
  authorization: "",
  pagination: "",
  "schema-design": "Schema Design",
  "global-object-identification": "",
  caching: "",
  performance: "",
  security: "",
  federation: "",
}
