export const tagColors = {
  newsletter: "#FFCCEF",
  announcements: "#F80",
  blog: "#298cc5",
  foundation: "#5800FF",
  spec: "#00C6AC",
  grants: "#84BD01",
  "in-the-news": "#3F3A3D",
  "developer-experience": "#6fc9af",

  backend: "#36C1A0",
  "defies-categorization": "#894545",
  "federation-and-composite-schemas": "#cbc749",
  "graphql-clients": "#ca78fc",
  "graphql-in-production": "#e4981f",
  "graphql-security": "#CC6BB0",
  "graphql-spec": "#6B73CC",
  scaling: "#8D8D8D",
  frontend: "violet",
  documentation: "salmon",
  "schema-evolution": "thistle",
  security: "cornflowerblue",
  "case-studies": "#B36B00",
  "federation-and-distributed-systems": "#FF8F70",
  federation: "#5C7CFA",
  tools: "#0FA3B1",
  "api-platform-and-gateways": "#F4B400",
  "schema-design": "#7E57C2",
  ai: "#FF5FA2",
  monitoring: "#2D9CDB",
  "blog-or-newsletter": "hsl(var(--color-pri-base))",
  book: "#00C6AC",
  guide: "#FF8800",
  video: "hsl(var(--color-pri-dark))",
  "tools-and-libraries": "hsl(var(--color-sec-dark))",
  list: "#00C6AC",
  post: "#FF8800",
} satisfies Record<string, string>
