export const videos = [
    { id: 'b45lWgkVLYA', title: `Top 10 GraphQL Security Checks for Every Developer - Ankita Gupta, Ankush Jain - Akto.io` },
    { id: 'kLUbcEABH0s', title: `GraphQL as a Data Mesh Access Layer in Global Banking - Kenneth Stott, Hasura Inc.` },
    { id: 'VqVBGM4XEiE', title: `Keynote: GraphQL In The House - Andrew Doyle, US House of Representatives` },
    { id: '8W9N-I1G80o', title: `Workshop: Cross-Platform GraphQL &amp; State Management with React Native - Yassin Eldeeb, The Guild` },
    { id: 'jv8q7kFyxo0', title: `Identity and GraphQL: More Than You Want to Think About IDs - Matt Mahoney, Meta` },
    { id: 'voeWmS-48Ag', title: `Spec Agnostic Executor for Federated GraphQL - Denis Badurina, The Guild` },
    { id: '0IcZGcO9Vm0', title: `GraphQL in the Era of React Server Components - Roy Derks, IBM` },
    { id: 't9swX1jpLSU', title: `Keynote: Closing Remarks - Sasha Solomon` },
    { id: 'yrhGfVOzxbU', title: `GraphQL &amp; Newcomers: How an API Can Transform Technical &amp; Functionnal Onboarding - Vincent Desmares` },
    { id: 'PGBC-0E-kco', title: `GraphQL Pagination at Meta - Sabrina Wasserman, Meta` },
    { id: 'ex8dqeWwt5A', title: `Revolutionizing Data Access Using GraphQL in the Oracle Database -  Shashank Gugnani, Oracle` },
    { id: 'v3dY3Y9VHJ8', title: `6 Years of Distributed GraphQL in Production - Andreas Marek, Atlassian` },
    { id: 'U4gCky2TFWE', title: `Schema-Driven UI Components: Innovating Headless ERP - Seiya Izumi, Masanori Uehara - Tailor, Inc.` },
    { id: 'Zjz2ou41-LI', title: `GraphQL Field Discovery &amp; Query Generation with Generative AI - Rachit Sengupta, Siva Thiru - Intuit` },
    { id: 'cEijqq-KQsU', title: `GraphQL at the Edge with WebAssembly - Ramnivas Laddad, Exograph Inc` },
    { id: 'szGCeD_UzmY', title: `The Power of Strongly Coupled GraphQL Queries for Internal APIs - Mary Briskin, Tutored by Teacher` },
    { id: 'wqRKO_vLY_c', title: `Keynote: GraphQL Clients in 2024 - Jeff Auriemma, Apollo GraphQL` },
    { id: '3UbcTEV54bI', title: `Keynote: TSC Panel - Lee Byron, Kewei Qu, Rob Richard, Michael Staib, &amp; Sasha Solomon` },
    { id: 'hFmJgR0vssY', title: `Schema-Driven Testing with Mock Service Worker - Alessia Bellisario, Apollo` },
    { id: 'ZDECb__f4h4', title: `Workshop: Scaling and Securing API Development with a GraphQL Platform- Laurin Quast &amp; Kamil Kisiela` },
    { id: 'GnjMUsvDcL4', title: `Converging Paramount EPG Architectures with GraphQL - Giacomo Simmi &amp; Satish Chitnis w/Paramount` },
    { id: '90dc_NelaA0', title: `UNSET Fields: Contrasting Null and Purposeful Omissions in Server Response - Janette Cheng, Meta` },
    { id: '_TSYKAtaK5A', title: `Build Confidently: How @Catch and Error Handling Pave Way in Field Nullability - Itamar Kestenbaum` },
    { id: 'CFIqWwWLSb8', title: `Consuming GraphQL in TypeSafe Languages - Anthony Miller, Apollo GraphQL` },
    { id: 'IzJeffH_x_s', title: `GraphQL Docs: Beyond the Schema - Sarah Sanders - Highnote` },
    { id: '9gY1vNw7Kcc', title: `Incrementally Adopting GraphQL and Relay at Pinterest - Mauricio Montalvo, Pinterest` },
    { id: 'w7ubbGmadso', title: `Not Your Regular Rate Limiting GraphQL - Pooja Mistry, Postman` },
    { id: 'vLFWJ5FO7GI', title: `Sponsored Keynote: GraphQL, BFFs and AI - Anant Jhingran, IBM` },
    { id: 'xaTEuk-DKqI', title: `Keynote - You&#39;re Our Universe: GraphQL Community Update 2024 - Benjie Gillam, Graphile` },
    { id: 'M3wGkC7rzmE', title: `Dynamically Serving a GraphQL API with Custom Types at Runtime - Emily Li Benchling` },
    { id: 'dDj6FF0y2YA', title: `GraphQL Is for Client Developers Not Client Applications - Michael Bleigh, Google` },
    { id: 'sf8ac2NtwPY', title: `Performing Impossible Feats with Isograph - Robert Balicki, Pinterest` },
    { id: '0K_Sp0g1ogc', title: `Keynote: Empathy Driven Development - Sarah Sanders, Highnote` },
    { id: 'QbuRTGdt4fA', title: `Keynote: Apollo&#39;s Journey with GraphQL: Transforming Enterprise APIs for the Future- Matt DeBergalis` },
    { id: 'V4CJR_vkELo', title: `Comparing API Protocols - One Feature at a Time - Uri Goldshtein, The Guild` },
    { id: '45rKrmW7NLA', title: `Blueprints of Successful GraphQL Architectures - Pascal Senn, ChilliCream` },
    { id: 'K9HCb5Q2Juc', title: `GraphQL Federation in the Wild - Stefan Avram, Wundergraph` },
    { id: 'Esb7oQ0PuXw', title: `Lessons from Scaling GraphQL to Half a Billion Requests per Minute - Tushar Mathur, Tailcall` },
    { id: 'kpeVT7J6Bsw', title: `Schema First, Code First, or Both? Adopting Schema First Development - Dan Adajian, Expedia Group` },
    { id: 'W7qIux5BAvs', title: `Techniques to Protect Your GraphQL API - Benjie Gillam, Graphile` },
    { id: 'U3m0J8HFuqQ', title: `How to Not Break Your GraphQL Clients - Pascal Senn, ChilliCream` },
    { id: 'vb4T51DO3Z4', title: `What if ... How to Achieve GraphQL Domination - Andreas Marek, Atlassian` },
    { id: '4xCcSqdablo', title: `Schema Scoring: Ensuring Schema Excellence in GraphQL - Christian Ernst -  Booking.com` },
    { id: 'r4ryfiBfDIQ', title: `GraphQL Subscriptions in Production Is Easy Isnt It? - Laurin Quast,The Guild` },
    { id: '5DpIO-isCMQ', title: `Keynote: Closing Remarks - Lee Byron, GraphQL Foundation` },
    { id: 'WZjwk_tRgvA', title: `The Intersection of GraphQL &amp; Design Systems in Product Dev. - Ruben Cagnie &amp; Alan Quigley - Toast` },
    { id: 'Ef6qv26fZHk', title: `State of @Defer and @Stream - Rob Richard, 1stDibs` },
    { id: 'eb8EoGGZCjY', title: `Design Principles of Federated GraphQL - Martijn Walraven - Apollo` },
    { id: 'x2tnnh9KKVs', title: `Sponsored Session: GraphQLs Future is Rooted in Governance - Adam Malone, Hasura` },
    { id: 'lKZMcixWf3o', title: `Sponsored Session: Championing GraphQL Client in a Modern Platform - Jeff Auriemma, Apollo GraphQL` },
    { id: 'jreLGIzgZ9U', title: `In-House Schema Registry - The Good the Bad and the Ugly - Kamil Kisiela, The Guild` },
    { id: 'ZilgUSmo_hA', title: `Why You Should Use Implementation-First to Build Your GraphQL Schema   Erik Wrede fulfillmenttools` },
    { id: 'andRX3esq9s', title: `Workshop: Getting Data Ready for AI - With Unified GraphQL &amp;SQL Endpoints - Anushrut Gupta, Hasura` },
    { id: 'eXWXRF6gYg8', title: `In Memory of Travails - Gabriel Schulhof, Auction.com` },
    { id: 'Nol_i1wZMOY', title: `What Could Go Wrong with a GraphQL Query &amp; Can OpenTelemetry Help?   Budha Bhattacharya, Tyk` },
    { id: 'tjmPJGMPZGQ', title: `Unlocking Blockchain Data with GraphQL - Saihajpreet Singh, The Guild` },
    { id: 'VgndfUI_xKI', title: `Keynote: Welcome Back &amp; Opening Remarks - Sasha Solomon` },
    { id: 'SFQB8F0Ofcg', title: `Ahead-of-Time (AOT) Techniques Help You Write GraphQL Libraries! - Mike Solomon` },
    { id: 'LbANoddAVic', title: `200 Is Not OK: Strategies for Tracing Partial Responses w/ GraphQL - Aditi Rajawat, Rama Palaniappan` },
    { id: 'obMcFwqtvUQ', title: `Improve Application Performance and User Engagement with Advanced GraphQL Features - Kewei Qu, Meta` },
    { id: 'A8T1QHJj0WM', title: `Keynote: The State of Distributed GraphQL - Michael Staib, ChilliCream Inc` },
    { id: 'tuStK4r8AaI', title: `A Wild GraphQL Rollercoaster Ride a Federated GraphQL Adoption Story - Lars de Bruijn &amp; An Ngo, bol` },
    { id: 'kmxy32cDRT8', title: `Building a Serverless GraphQL Subscription Gateway - Christian Stan &amp;  Kenneth Wußmann w/MOIA GmbH` },
    { id: 'Q8l9u5K5VBA', title: `Sponsored Keynote: Uri Goldshtein, The Guild` },
    { id: 'ES-wIMcUyfs', title: `Sponsored Session: From Prototype to Production: Building Custom GraphQL APIs - Kevin Brown, Exogee` },
    { id: '4XbzBb_YHw0', title: `Panel: The Composite Schemas Working Group - The Guild, ChilliCream &amp; Apollo` },
    { id: 'FTzPajvTw4c', title: `Welcome - Opening Remarks - Lee Byron, GraphQL Foundation` },
    { id: 'O4I2BhHgYq8', title: `Workshop: Demand-Driven Schema Design - Michael Watson, Apollo GraphQL` },
    { id: '7psGsLQGwMc', title: `Panel: The Composite Schemas Working G... Kamil Kisiela, Pascal Senn, Martijn Walraven, Danielle Man` },
    { id: 'ek8Tj_F-xn8', title: `The Billion D∅Llar Panel - Nullability... S. Spalding, A. Reilly, J. Cheng &amp; J. Eldredge, B. Gillam` },
    { id: 'KPnWPz20r88', title: `Evolving GraphQL Schemas - Andrei Bocan, Atlassian` },
]
