export const eventsColors: Record<string, string> = {
  Breaks: "#7DAA5E",
  "Keynote Sessions": "#7e66cc",
  "Lightning Talks": "#1a5b77",
  "Session Presentations": "#5c2e75",
  Workshops: "#4b5fc0",
  Unconference: "#7e66cc",
  "API Platform": "#4e6e82",
  Backend: "#36C1A0",
  "Breaks & Special Events": "#7DAA5E",
  "Defies Categorization": "#894545",
  "Developer Experience": "#6fc9af",
  "Federation and Composite Schemas": "#cbc749",
  "GraphQL Clients": "#ca78fc",
  "GraphQL in Production": "#e4981f",
  "GraphQL Security": "#CC6BB0",
  "GraphQL Spec": "#6B73CC",
  Scaling: "#8D8D8D",
}
