export const eventsColors: Record<string, string> = {
  Breaks: "#7DAA5E",
  "Keynote Sessions": "#8A9CBF",
  "Lightning Talks": "#1a5b77",
  "Session Presentations": "#5c2e75",
  Workshops: "#4b5fc0",
  Unconference: "#7e66cc",
  "API Platform": "#4e6e82",
  Backend: "#36C1A0",
  "Breaks & Special Events": "#7DAA5E",
  "Defies Categorization": "#CCCC2A",
  "Developer Experience": "#9AC5B9",
  "Federation and Composite Schemas": "#CCC74E",
  "GraphQL Clients": "#C39ADC",
  "GraphQL in Production": "#CC9646",
  "GraphQL Security": "#CC6BB0",
  "GraphQL Spec": "#6B73CC",
  Scaling: "#8D8D8D",
}
