// This file is auto-generated, please contact local@graphql.org to update
export const meetups = [
  {
    node: {
      id: "london",
      name: "London GraphQL",
      latitude: 51.51,
      longitude: -0.12,
      city: "London",
      state: "",
      country: "UK",
      link: "https://guild.host/london-graphql",
      prev: "2025-07-01",
      next: "October 2025",
      official: true,
    },
  },
  {
    node: {
      id: "hyderabad",
      name: "GraphQL Hyderabad",
      latitude: 17.41,
      longitude: 78.48,
      city: "Hyderabad",
      state: "",
      country: "India",
      link: "https://guild.host/graphql-hyderabad/",
      prev: "2025-08-09",
      next: "",
      official: true,
    },
  },
  {
    node: {
      id: "sydney",
      name: "GraphQL Sydney",
      latitude: -33.86,
      longitude: 151.2,
      city: "Sydney",
      state: "",
      country: "Australia",
      link: "https://luma.com/graphql-sydney",
      prev: "2024-11-12",
      next: "",
      official: false,
    },
  },
  {
    node: {
      id: "nairobe",
      name: "GraphQL Nairobe",
      latitude: -1.29,
      longitude: 36.82,
      city: "Nairobe",
      state: "",
      country: "Kenya",
      link: "https://www.meetup.com/nairobi-graphql-meetup/",
      prev: "",
      next: "",
      official: false,
    },
  },
  {
    node: {
      id: "20451795",
      name: "GraphQL Austin",
      latitude: 30.27,
      longitude: -97.71,
      city: "Austin",
      state: "TX",
      country: "USA",
      link: "https://www.meetup.com/atx-graphql",
      prev: "2025-08-24",
      next: "",
      official: true,
    },
  },
  {
    node: {
      id: "31255122",
      name: "GraphQL SF",
      latitude: 37.78,
      longitude: -122.42,
      city: "San Francisco",
      state: "CA",
      country: "USA",
      link: "http://meetup.com/GraphQL-SF",
      prev: "",
      next: "",
      official: false,
    },
  },
  {
    node: {
      id: "31704787",
      name: "GraphQL Zurich",
      latitude: 47.38,
      longitude: 8.54,
      city: "Zurich",
      state: "",
      country: "Switzerland",
      link: "https://www.meetup.com/graphql-zurich",
      prev: "",
      next: "",
      official: false,
    },
  },
  {
    node: {
      id: "paris",
      name: "GraphQL Paris",
      latitude: 48.85,
      longitude: 2.35,
      city: "Paris",
      state: "",
      country: "France",
      link: "https://www.meetup.com/fr-FR/parisgraphql/",
      prev: "",
      next: "2025-10-22",
      official: true,
    },
  },
  {
    node: {
      id: "29671383",
      name: "Seattle GraphQL",
      latitude: 47.61,
      longitude: -122.33,
      city: "Seattle",
      state: "WA",
      country: "USA",
      link: "https://www.meetup.com/graphql-seattle",
      prev: "",
      next: "",
      official: false,
    },
  },
  {
    node: {
      id: "20208222",
      name: "GraphQL Amsterdam",
      latitude: 52.37,
      longitude: 4.89,
      city: "Amsterdam",
      state: "",
      country: "Netherlands",
      link: "https://www.meetup.com/amsterdam-graphql-meetup",
      prev: "2025-09-07",
      next: "",
      official: true,
    },
  },
  {
    node: {
      id: "37102548",
      name: "GraphQL Berlin",
      latitude: 52.52,
      longitude: 13.4,
      city: "Berlin",
      state: "",
      country: "Germany",
      link: "https://www.meetup.com/graphql-berlin/",
      prev: "2025-09-11",
      next: "",
      official: false,
    },
  },
  {
    node: {
      id: "new-york",
      name: "GraphQL New York",
      latitude: 40.73,
      longitude: -73.94,
      city: "New York",
      state: "NY",
      country: "USA",
      link: "https://guild.host/graphql-new-york/events",
      prev: "",
      next: "",
      official: false,
    },
  },
  {
    node: {
      id: "bangkok",
      name: "GraphQL Bangkok",
      latitude: 13.75,
      longitude: 100.5,
      city: "Bangkok",
      state: "",
      country: "Thailand",
      link: "https://www.meetup.com/graphql-bangkok",
      prev: "",
      next: "",
      official: false,
    },
  },
  {
    node: {
      id: "taipei",
      name: "GraphQL Taipei",
      latitude: 25.11,
      longitude: 121.6,
      city: "Taipei",
      state: "",
      country: "Taiwan",
      link: "https://guild.host/graphql-taipei/events",
      prev: "",
      next: "",
      official: false,
    },
  },
  {
    node: {
      id: "20446155",
      name: "GraphQL TLV",
      latitude: 32.07,
      longitude: 34.77,
      city: "Tel Aviv-Yafo",
      state: "",
      country: "Israel",
      link: "https://www.meetup.com/graphql-tlv",
      prev: "",
      next: "",
      official: false,
    },
  },
  {
    node: {
      id: "oslo",
      name: "GraphQL Oslo",
      latitude: 59.91,
      longitude: 10.75,
      city: "Oslo",
      state: "",
      country: "Norway",
      link: "https://guild.host/graphql-oslo/",
      prev: "2025-10-27",
      next: "2026-01-26",
      official: true,
    },
  },
  {
    node: {
      id: "bialystock",
      name: "GraphQL Białystok",
      latitude: 53.13,
      longitude: 23.16,
      city: "Białystok",
      state: "",
      country: "Poland",
      link: "https://guild.host/graphql-bialystok/",
      prev: "",
      next: "",
      official: true,
    },
  },
  {
    node: {
      id: "32869172",
      name: "Copenhagen GraphQL",
      latitude: 55.68,
      longitude: 12.57,
      city: "Copenhagen",
      state: "",
      country: "Denmark",
      link: "https://www.meetup.com/copenhagen-graphql-meetup-group",
      prev: "",
      next: "",
      official: false,
    },
  },
  {
    node: {
      id: "27845373",
      name: "GraphQL Hamburg",
      latitude: 53.55,
      longitude: 10,
      city: "Hamburg",
      state: "",
      country: "Germany",
      link: "https://www.meetup.com/graphql-hamburg/",
      prev: "",
      next: "",
      official: false,
    },
  },
  {
    node: {
      id: "philly",
      name: "Philly GraphQL",
      latitude: 39.9526,
      longitude: -75.1652,
      city: "Philadelphia",
      state: "PA",
      country: "USA",
      link: "https://luma.com/phillygraphql",
      prev: "",
      next: "2026-01-22",
      official: true,
    },
  },
].sort((a, z) =>
  a.node.name
    .replace(/\s*GraphQL\s*/, "")
    .localeCompare(z.node.name.replace(/\s*GraphQL\s*/, "")),
)
