name: lint & test

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: the-guild-org/shared-config/setup@main
        name: setup env
        with:
          packageManager: pnpm
          workingDirectory: ./

      - name: Install Dependencies
        run: pnpm i

      - name: Run ESLint
        run: pnpm lint --quiet

      - name: Run Prettier Check
        run: pnpm format:check

      - name: Validate code snippets
        run: pnpm validate:snippets

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: the-guild-org/shared-config/setup@main
        name: setup env
        with:
          packageManager: pnpm
          workingDirectory: ./

      - name: Install Dependencies
        run: pnpm i

      - name: Run unit tests
        run: pnpm test:unit

  playwright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: the-guild-org/shared-config/setup@main
        name: setup env
        with:
          packageManager: pnpm
          workingDirectory: ./

      - name: Install Dependencies
        run: pnpm i

        # per the docs: "caching browser binaries is not recommended,
        # since the amount of time it takes to restore the cache is
        # comparable to the time it takes to download the binaries"
      - name: Install Playwright Browsers
        run: ./node_modules/.bin/playwright install --with-deps

      - name: Build the website
        run: pnpm build

      - name: Run end-to-end tests
        run: ./node_modules/.bin/playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      # - uses: valeriangalliat/action-sshd-cloudflared@v1
      #   if: failure()
