# Sched's API rate limits are very limited, so we sync non-critical part of the data on a cron.
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *" # Every 3 hours

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger redeploy
        run: curl --fail --silent --show-error -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }} >/dev/null
