# Sched's API rate limits are very limited, so we sync non-critical part of the data on a cron.
on:
  workflow_dispatch:
  # schedule:
  # - cron: "*/10 * * * *" # every ten minutes

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync conference data from Sched
        run: |
          tsx scripts/sync-sched/sync.ts --year 2026
        env:
          SCHED_ACCESS_TOKEN_2026: ${{ secrets.SCHED_ACCESS_TOKEN_2026 }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: "scripts/sync-sched/*.json"
          commit_message: "Sync conference data from Sched"
