# Docs validation workflow runs on each PR on main w/ broken link checker
# and code snippet validation

name: Docs validation

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
link-check:
  name: Broken link checker
  runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build static site
      run: pnpm build

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install lychee
      run: cargo install lychee

    - name: Check links
      run: lychee --verbose --no-progress './out/**/*.html'

code-validate:
  name: Code snippet and GraphQL validation
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Run validation w/ annotations
      run: pnpm lint:docs:ci

    - name: Validate code snippets
      run: pnpm validate:snippets
